############################
#         VERSIONS         #
############################
[versions]

# Build Plugins
android-gradlePlugin = "8.3.2"
kotlin = "2.1.0"
ksp = "2.1.0-1.0.29"

# UI Components
material = "1.11.0"
appcompat = "1.6.1"
coreKtx = "1.12.0"
activity = "1.8.2"
activityKtx = "1.9.0"
constraintlayout = "2.1.4"

# Lifecycle / Architecture
lifecycleViewmodel = "2.6.2"

# Dependency Injection
daggerHilt = "2.56.2"
hiltAndroid = "2.56.2"

# Image Loading
glide = "4.16.0"
picasso = "2.8"

# Testing
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"


############################
#        LIBRARIES         #
############################
[libraries]

# UI Components
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# Lifecycle / Architecture Components
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodel" }

# Dependency Injection (Hilt)
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }

# Image Loading
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }


############################
#         PLUGINS          #
############################
[plugins]

# Android / Kotlin Plugins
androidApplication = { id = "com.android.application", version.ref = "android-gradlePlugin" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Annotation Processing
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Dependency Injection (Hilt)
daggerHilt = { id = "com.google.dagger.hilt.android", version.ref = "daggerHilt" }
